version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/NeighborGoods.Frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
