// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeighborGoods.Api.Shared.Persistence;

#nullable disable

namespace NeighborGoods.Api.Migrations
{
    [DbContext(typeof(NeighborGoodsDbContext))]
    [Migration("20260423021932_AddQuickResponderBadgeFields")]
    partial class AddQuickResponderBadgeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(9);

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCharity")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTradeable")
                        .HasColumnType("bit");

                    b.Property<int>("PickupLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("PinnedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PinnedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("Residence")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Condition");

                    b.HasIndex("PickupLocation");

                    b.HasIndex("Residence");

                    b.HasIndex(new[] { "BuyerId" }, "IX_Listings_BuyerId");

                    b.HasIndex(new[] { "SellerId" }, "IX_Listings_SellerId");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeKey")
                        .IsUnique();

                    b.ToTable("ListingCategories", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingCondition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeKey")
                        .IsUnique();

                    b.ToTable("ListingConditions", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategorySnapshot")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingFavorites_ListingId");

                    b.HasIndex(new[] { "UserId", "CategorySnapshot", "CreatedAt" }, "IX_ListingFavorites_UserId_CategorySnapshot_CreatedAt");

                    b.HasIndex(new[] { "UserId", "ListingId" }, "IX_ListingFavorites_UserId_ListingId")
                        .IsUnique();

                    b.ToTable("ListingFavorites", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingPickupLocation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeKey")
                        .IsUnique();

                    b.ToTable("ListingPickupLocations", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingResidence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeKey")
                        .IsUnique();

                    b.ToTable("ListingResidences", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AdminMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SenderId" }, "IX_AdminMessages_SenderId");

                    b.ToTable("AdminMessages");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailNotificationEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailNotificationLastSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsQuickResponder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LineMessagingApiAuthorizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineMessagingApiUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LineNotificationLastSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineNotificationPreference")
                        .HasColumnType("int");

                    b.Property<string>("LineUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("QuickResponderEvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuickResponderP75Minutes")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopPinCredits")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Participant1Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Participant1LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Participant2Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Participant2LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ListingId" }, "IX_Conversations_ListingId");

                    b.HasIndex(new[] { "Participant1Id", "Participant2Id", "ListingId" }, "IX_Conversations_Participant1Id_Participant2Id_ListingId");

                    b.HasIndex(new[] { "Participant2Id" }, "IX_Conversations_Participant2Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.EmailVerificationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Purpose")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Purpose", "NormalizedEmail", "ConsumedAt", "ExpiresAt" }, "IX_EmailVerificationChallenges_Purpose_Email_Consumed_Expires");

                    b.HasIndex(new[] { "UserId", "Purpose", "ConsumedAt" }, "IX_EmailVerificationChallenges_User_Purpose_Consumed");

                    b.ToTable("EmailVerificationChallenges", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.LineBindingPending", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LineUserId" }, "IX_LineBindingPending_LineUserId");

                    b.HasIndex(new[] { "Token" }, "IX_LineBindingPending_Token")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_LineBindingPending_UserId");

                    b.ToTable("LineBindingPending", (string)null);
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingImages_ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.ListingTopSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowPromotion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackDetail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeedbackTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GrantedCredits")
                        .HasColumnType("int");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoBlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByAdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ListingTopSubmissions_CreatedAt");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingTopSubmissions_ListingId");

                    b.HasIndex(new[] { "ReviewedByAdminId" }, "IX_ListingTopSubmissions_ReviewedByAdminId");

                    b.HasIndex(new[] { "Status" }, "IX_ListingTopSubmissions_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_ListingTopSubmissions_UserId");

                    b.ToTable("ListingTopSubmissions");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConversationId" }, "IX_Messages_ConversationId");

                    b.HasIndex(new[] { "SenderId" }, "IX_Messages_SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SellerReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BuyerId" }, "IX_PurchaseRequests_BuyerId");

                    b.HasIndex(new[] { "ConversationId" }, "IX_PurchaseRequests_ConversationId");

                    b.HasIndex(new[] { "ListingId", "CreatedAt" }, "IX_PurchaseRequests_ListingId_CreatedAt");

                    b.HasIndex(new[] { "ListingId", "Status" }, "IX_PurchaseRequests_ListingId_Status")
                        .IsUnique()
                        .HasFilter("([Status]=(0))");

                    b.HasIndex(new[] { "SellerId", "Status" }, "IX_PurchaseRequests_SellerId_Status");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BuyerId" }, "IX_Reviews_BuyerId");

                    b.HasIndex(new[] { "ListingId", "BuyerId" }, "IX_Reviews_ListingId_BuyerId")
                        .IsUnique();

                    b.HasIndex(new[] { "SellerId" }, "IX_Reviews_SellerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.Listing", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Buyer")
                        .WithMany("ListingBuyers")
                        .HasForeignKey("BuyerId");

                    b.HasOne("NeighborGoods.Api.Features.Listing.ListingCategory", "CategoryInfo")
                        .WithMany("Listings")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Features.Listing.ListingCondition", "ConditionInfo")
                        .WithMany("Listings")
                        .HasForeignKey("Condition")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Features.Listing.ListingPickupLocation", "PickupLocationInfo")
                        .WithMany("Listings")
                        .HasForeignKey("PickupLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Features.Listing.ListingResidence", "ResidenceInfo")
                        .WithMany("Listings")
                        .HasForeignKey("Residence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Seller")
                        .WithMany("ListingSellers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CategoryInfo");

                    b.Navigation("ConditionInfo");

                    b.Navigation("PickupLocationInfo");

                    b.Navigation("ResidenceInfo");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingFavorite", b =>
                {
                    b.HasOne("NeighborGoods.Api.Features.Listing.Listing", "Listing")
                        .WithMany("Favorites")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AdminMessage", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Sender")
                        .WithMany("AdminMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetRoleClaim", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUserClaim", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUserLogin", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUserToken", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Conversation", b =>
                {
                    b.HasOne("NeighborGoods.Api.Features.Listing.Listing", "Listing")
                        .WithMany("Conversations")
                        .HasForeignKey("ListingId")
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Participant1")
                        .WithMany("ConversationParticipant1s")
                        .HasForeignKey("Participant1Id")
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Participant2")
                        .WithMany("ConversationParticipant2s")
                        .HasForeignKey("Participant2Id")
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Participant1");

                    b.Navigation("Participant2");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.LineBindingPending", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "User")
                        .WithMany("LineBindingPendings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.ListingImage", b =>
                {
                    b.HasOne("NeighborGoods.Api.Features.Listing.Listing", "Listing")
                        .WithMany("ListingImages")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.ListingTopSubmission", b =>
                {
                    b.HasOne("NeighborGoods.Api.Features.Listing.Listing", "Listing")
                        .WithMany("ListingTopSubmissions")
                        .HasForeignKey("ListingId");

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "ReviewedByAdmin")
                        .WithMany("ListingTopSubmissionReviewedByAdmins")
                        .HasForeignKey("ReviewedByAdminId");

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "User")
                        .WithMany("ListingTopSubmissionUsers")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Message", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.PurchaseRequest", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Buyer")
                        .WithMany("PurchaseRequestBuyers")
                        .HasForeignKey("BuyerId")
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Conversation", "Conversation")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Features.Listing.Listing", "Listing")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Seller")
                        .WithMany("PurchaseRequestSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Conversation");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Review", b =>
                {
                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Buyer")
                        .WithMany("ReviewBuyers")
                        .HasForeignKey("BuyerId")
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Features.Listing.Listing", "Listing")
                        .WithMany("Reviews")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", "Seller")
                        .WithMany("ReviewSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.Listing", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Favorites");

                    b.Navigation("ListingImages");

                    b.Navigation("ListingTopSubmissions");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingCategory", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingCondition", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingPickupLocation", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("NeighborGoods.Api.Features.Listing.ListingResidence", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.AspNetUser", b =>
                {
                    b.Navigation("AdminMessages");

                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("ConversationParticipant1s");

                    b.Navigation("ConversationParticipant2s");

                    b.Navigation("LineBindingPendings");

                    b.Navigation("ListingBuyers");

                    b.Navigation("ListingSellers");

                    b.Navigation("ListingTopSubmissionReviewedByAdmins");

                    b.Navigation("ListingTopSubmissionUsers");

                    b.Navigation("Messages");

                    b.Navigation("PurchaseRequestBuyers");

                    b.Navigation("PurchaseRequestSellers");

                    b.Navigation("ReviewBuyers");

                    b.Navigation("ReviewSellers");
                });

            modelBuilder.Entity("NeighborGoods.Api.Shared.Persistence.LegacyEntities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("PurchaseRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
